language: php
php:
  - '7.2'
before_script:
  - composer install
  - composer dump-autoload
script:
  - ./phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)